name: 'coverage'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  coverage:
    permissions:
      pull-requests: write
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r ci/requirements.txt
          echo "setuptools bug on 3.12 see https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources"
          pip install setuptools
      - name: Pytest
        run: |
          pytest -vv --cov=./ --cov-report xml:coverage.xml
      - name: Get Cover
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml
          thresholdAll: 0
          thresholdNew: 0
          thresholdModified: 0
          token: ${{ secrets.GITHUB_TOKEN }}